version: '3'
services:
  php:
    container_name: angular-test
    build: ./
    ports:
    - 80:80
    volumes:
    - ./www:/var/www/html
    networks:
      - my-network

networks:
  my-network:

volumes:
  data:

